version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: creditCard
    ports:
      - "5423:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: